development:
  cloud_name: sdcnwco
  api_key: <%= Rails.application.credentials.cloudinary[:API_KEY] %>
  api_secret: <%= Rails.application.credentials.cloudinary[:SECRET_API_KEY] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: sdcnwco
  api_key: <%= Rails.application.credentials.cloudinary[:API_KEY] %>
  api_secret: <%= Rails.application.credentials.cloudinary[:SECRET_API_KEY] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: sdcnwco
  api_key: <%= Rails.application.credentials.cloudinary[:API_KEY] %>
  api_secret: <%= Rails.application.credentials.cloudinary[:SECRET_API_KEY] %>
  enhance_image_tag: true
  static_file_support: false
